code/TestcaseExtraction/UnitTestScribe/Subjects/Glimpse-master/source/Glimpse.Mvc5.MusicStore.Sample/Controllers/ModelBindingTestsController.cs
using System.Collections.Generic;
using System.Web.ModelBinding;
using System.Web.Mvc;

namespace MvcMusicStore.Controllers
{
    public class ModelBindingTestsController : Controller
    {
        public ActionResult Index()
        {
            return View("Index", new ComplexType());
        }

        [HttpPost]
        public ActionResult SimplePost(string firstname, string lastname)
        {
            return View("Index", new ComplexType());
        }

        [HttpPost]
        public ActionResult ComplexPost(ComplexType complexType, string additionalSimpleValue)
        {
            return View("Index", new ComplexType());
        }

        [HttpPost]
        public JsonResult PostItem(AjaxPostedData item)
        {
            return new JsonResult { Data = new { PostedItem = item } };
        }

        [HttpPost]
        public ActionResult HtmlContainedPost(HtmlInputAllowedType htmlInputAllowedType)
        {
            return View("Index", new ComplexType());
        }

        public class AjaxPostedData
        {
            public string MySimpleValue { get; set; }
            public Dictionary<string, string> MyStringDictionary { get; set; }
            public Dictionary<string, MyComplexObject> MyComplexObjectDictionary { get; set; }
            public MyComplexObject MyComplexObject { get; set; }
            public string[] MyStringArray { get; set; }
        }

        public class MyComplexObject
        {
            public string Name { get; set; }
            public string Value { get; set; }
        }

        public class ComplexType
        {
            public ComplexType()
            {
                this.Name = "Foo";
                this.Another = new SecondLevelComplexType();
            }

            public string Name { get; set; }
            public SecondLevelComplexType Another { get; set; }
        }

        public class SecondLevelComplexType
        {
            public SecondLevelComplexType()
            {
                this.Name = "Bar";
                this.Values = new ThirdLevelComplexType(this.Name);
            }

            public string Name { get; set; }
            public ThirdLevelComplexType Values { get; set; }
        }

        public class ThirdLevelComplexType
        {
            public ThirdLevelComplexType(string valueFor)
            {
                this.Value1 = "Value 1 for " + valueFor;
                this.Value2 = "Value 2 for " + valueFor;
            }

            public string Value1 { get; set; }
            public string Value2 { get; set; }
        }

        public class HtmlInputAllowedType
        {
            [AllowHtml]
            public string HtmlContent { get; set; }
        }
    }
}

code/TestcaseExtraction/UnitTestScribe/Subjects/Glimpse-master/source/Glimpse.Mvc5.MusicStore.Sample/Views/ModelBindingTests/Index.cshtml
@model MvcMusicStore.Controllers.ModelBindingTestsController.ComplexType
@{
    ViewBag.Title = "ModelBindng Tests";
}

<h2>By clicking on the button, an Ajax call will be made for an item and the returned item should be the same</h2>

<input type="button" id="PostItem" name="PostItem" value="Post Ajax item" />
<br /><hr/><br />
@using (Html.BeginForm("SimplePost", "ModelBindingTests", FormMethod.Post))
{
    <label for="FirstName">First name :</label><input type="text" id="FirstName" name="FirstName" value="Foo" /><br/>
    <label for="LastName">Last name :</label><input type="text" id="LastName" name="LastName" value="Bar" />
    <input type="submit" value="Normal post"/>
}
<br /><hr /><br />
@using (Html.BeginForm("ComplexPost", "ModelBindingTests", FormMethod.Post))
{
    @Html.LabelFor(m=> m.Name, "Name :") 
    @Html.TextBoxFor(m=> m.Name)
    <br/>
    @Html.LabelFor(m=> m.Name, "Another Name :") 
    @Html.TextBoxFor(m=> m.Another.Name)
    <br/>
    @Html.LabelFor(m=> m.Name, "Another Value 1 :") 
    @Html.TextBoxFor(m=> m.Another.Values.Value1) <br/>
    @Html.LabelFor(m=> m.Name, "Another Value 2 :") 
    @Html.TextBoxFor(m=> m.Another.Values.Value2)
    <br/>
    <label for="additionalSimpleValue">Additional simple value :</label>
    <input type="text" id="additionalSimpleValue" name="additionalSimpleValue" value="the additional value"/>
    <input type="submit" value="Normal post with complex type"/>
}
<br /><hr /><br />
@using (Html.BeginForm("HtmlContainedPost", "ModelBindingTests", FormMethod.Post))
{
    <label for="HtmlContent">HTML content :</label><input type="text" id="HtmlContent" name="HtmlContent" />
    <input type="submit" value="Post HTML value" />
}

@section scripts
{
    <script type="text/javascript">
        $(function () {
            $("#HtmlContent").val('<html><body>HTML content</body></html>');

            $("#PostItem").click(function () {
                
                var item = JSON.stringify(
                    {
                        MySimpleValue: "some simple value",
                        MyStringDictionary: { "Key1": "Key1Value", "Key2": "Key2Value" },
                        MyComplexObjectDictionary : {
                            "FirstComplexObject" : { Name : "First complex object name", Value : "First complex object value" },
                            "SecondComplexObject" : { Name : "Second complex object name", Value : "Second complex object value" }
                        },
                        MyComplexObject : {
                            Name: "some name",
                            Value: "some value"
                        },
                        MyStringArray : ["First","Second","Third"]
                    });
                
                $.ajax({
                    url: '@Url.Action("PostItem", "ModelBindingTests")',
                    type: 'POST',
                    dataType: 'json',
                    contentType: 'application/json',
                    data: item,
                    success: function (result) {
                        alert('Item posted as :\n' + item + '\n\nItem received as :\n' + JSON.stringify(result.PostedItem));
                    },
                    error: function () {
                        alert('Posting item failed');
                    }
                });
            });
        });
    </script>
}